config/routes.rb
ParkingSpot::Application.routes.draw do
  resources :parking_registrations

  root 'parking_registrations#new'

end

app/models/parking_registration.rb
class ParkingRegistration < ActiveRecord::Base
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :spot_number
  validates_presence_of :parked_on

  validates_format_of :email, with: /.+\@.+\..+/

  validates_numericality_of :spot_number,
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 60

  def park
    if occupied?(spot_number)
      errors.add(:spot_number, "Sorry, this spot is taken.")
      return false
    end
    self.parked_on = Date.today
    save
  end

  def occupied?(spot)
    ParkingRegistration.where(spot_number: spot).where(parked_on: Date.today).any?
  end

  def neighbors
    low_neighbor = ParkingRegistration.where({
        spot_number: self.spot_number - 1,
        parked_on: self.parked_on
        }).first

    high_neighbor = ParkingRegistration.where({
        spot_number: self.spot_number + 1,
        parked_on: self.parked_on
        }).first

    [low_neighbor, high_neighbor]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/parking_registrations_controller.rb
class ParkingRegistrationsController < ApplicationController
  before_action :set_parking_registration, only: [:show, :edit, :update, :destroy]

  # GET /parking_registrations
  # GET /parking_registrations.json
  def index
    @parking_registrations = ParkingRegistration.all
  end

  # GET /parking_registrations/1
  # GET /parking_registrations/1.json
  def show
    @parking_registration = ParkingRegistration.find(params[:id])
  end

  # GET /parking_registrations/new
  def new
    if session[:parking_registration_id]
      @email = ParkingRegistration.find(session[:parking_registration_id]).email
    end
    @parking_registration = ParkingRegistration.new
  end

  # GET /parking_registrations/1/edit
  def edit
  end

  # POST /parking_registrations
  # POST /parking_registrations.json
  def create
    @parking_registration = ParkingRegistration.new(parking_registration_params)

    if @parking_registration.park
      session[:parking_registration_id] = @parking_registration.id
      flash[:notice] = 'You registered successfully.'
      redirect_to "/parking_registrations/#{@parking_registration.id}"
    else
      render :new
    end
  end

  # PATCH/PUT /parking_registrations/1
  # PATCH/PUT /parking_registrations/1.json
  def update
    respond_to do |format|
      if @parking_registration.update(parking_registration_params)
        format.html { redirect_to @parking_registration, notice: 'Parking registration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parking_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_registrations/1
  # DELETE /parking_registrations/1.json
  def destroy
    @parking_registration.destroy
    respond_to do |format|
      format.html { redirect_to parking_registrations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_registration
      @parking_registration = ParkingRegistration.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parking_registration_params
      params.require(:parking_registration).permit(:first_name, :last_name, :email, :spot_number, :parked_on)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parking_registrations_helper.rb
module ParkingRegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParkingSpot</title>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <%= notice %>
  <%= yield %>

</div>

</body>
</html>

app/views/parking_registrations/_form.html.erb
<%= form_for(@parking_registration, html: { class: 'form' }) do |f| %>
  <% if @parking_registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parking_registration.errors.count, "error") %> prohibited this parking_registration from being saved:</h2>

      <ul>
      <% @parking_registration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :value => @email %>
  </div>
  <div class="field">
    <%= f.label :spot_number %><br>
    <%= f.number_field :spot_number %>
  </div>
  <!--
  <div class="field">
    <%= f.label :parked_on %><br>
    <%= f.date_select :parked_on %>
  </div> -->
  <div class="actions">
    <%= f.submit 'Register' %>
  </div>
<% end %>

app/views/parking_registrations/edit.html.erb
<h1>Editing parking_registration</h1>

<%= render 'form' %>

<%= link_to 'Show', @parking_registration %> |
<%= link_to 'Back', parking_registrations_path %>

app/views/parking_registrations/index.html.erb
<h1>Listing parking_registrations</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Spot number</th>
      <th>Parked on</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parking_registrations.each do |parking_registration| %>
      <tr>
        <td><%= parking_registration.first_name %></td>
        <td><%= parking_registration.last_name %></td>
        <td><%= parking_registration.email %></td>
        <td><%= parking_registration.spot_number %></td>
        <td><%= parking_registration.parked_on %></td>
        <td><%= link_to 'Show', parking_registration %></td>
        <td><%= link_to 'Edit', edit_parking_registration_path(parking_registration) %></td>
        <td><%= link_to 'Destroy', parking_registration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parking registration', new_parking_registration_path %>

app/views/parking_registrations/new.html.erb
<h1>New parking_registration</h1>

<%= render 'form' %>

<%= link_to 'Back', parking_registrations_path %>

app/views/parking_registrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% low_neighbor = @parking_registration.neighbors.first %>
  <% high_neighbor = @parking_registration.neighbors.last %>

  <%= "Low neighbor: #{low_neighbor.first_name}" if low_neighbor %>
  <%= "High neighbor: #{high_neighbor.first_name}" if high_neighbor %>
  <%= "You have no neighbors" if low_neighbor.nil? and high_neighbor.nil? %>
</p>

<p>
  <strong>Name:</strong>
  <%= @parking_registration.first_name %>
  <%= @parking_registration.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @parking_registration.email %>
</p>

<p>
  <strong>Spot number:</strong>
  <%= @parking_registration.spot_number %>
</p>

<p>
  <strong>Parked on:</strong>
  <%= @parking_registration.parked_on %>
</p>

<%= link_to 'Edit', edit_parking_registration_path(@parking_registration) %> |
<%= link_to 'Back', parking_registrations_path %>